### PR TITLE
fix mod types and settings

### PR DESCRIPTION
**Pull request by yorunoken**

### CODE REVIEW

**Comment by GabuTheDev** [comment]
Hey there! I suggest making a base interface and extend that for each mod.

**Comment by GabuTheDev** [comment]
I could do that for you, if you want ofc. (It's your PR after all)

**Comment by yorunoken** [comment]
yeah that's what I thought of doing but I'm kinda busy rn @GabuTheDev, I'll do it in a bit

**Comment by yorunoken** [comment]
did you mean something like this?
```ts
interface BaseMods {
  acronym: string;
}

interface EZ extends BaseMods {
  acronym: "EZ";
  settings?: {
    retries: number;
  };
}

interface NF {
  acronym: "NF";
}
```

**Comment by GabuTheDev** [comment]
> did you mean something like this?

Exactly. Should be called `BaseMod`, and the interface should already have an empty `settings` property.

**Comment by yorunoken** [comment]
@GabuTheDev the `settings` property is only included if there's a non-default setting being applied
if the mod doesn't support settings, it simply won't exist, so it's not a good idea to have that as its property

**Comment by yorunoken** [comment]
you can read all the mods' settings [here](https://raw.githubusercontent.com/ppy/osu-web/master/database/mods.json)

**Comment by GabuTheDev** [comment]
> @GabuTheDev the `settings` property is only included if there's a non-default setting being applied
> if the mod doesn't support settings, it simply won't exist, so it's not a good idea to have that as its property

My bad. Not so familiar with the osu API. Good to know, thank you!

**Comment by yorunoken** [comment]
@GabuTheDev no problem!

**Comment by yorunoken** [comment]
actually, you can just pass in a `?` after `settings` and it'll be fine, thanks for the recommendation @GabuTheDev

**Comment by yorunoken** [comment]
should be ready to merge now

**Comment by GabuTheDev** [comment]
@YoruNoKen Your PR will be reviewed by @cyperdark. This might not be merged directly as ck is working on a new version of this package. It also requires a lot of changes to the files that are using the `Mod` interface currently present in `main` branch so it might take a while until this change will go live (or maybe I'm wrong, final verdict comes from ck).

**Comment by yorunoken** [comment]
@GabuTheDev yea ik I talked with ck prior to making this pr, thanks for the attention :D

**Comment by yorunoken** [comment]
also, from what I can see, `Mod` is only used to infer a type, so it requires no changes to current files
image

**Comment by cyperdark** [comment]
will be done here https://github.com/cyperdark/osu-api-extended/pull/24

**Comment by yorunoken** [comment]
sure :)

**Pull request closed without merging**
