### PR TITLE
Refactor user authorization functions

### LINKED ISSUE #15: Suggestion: Refactor Function Signatures to Accept Object Parameters
### Here are some benefits of upgrading:
- **Flexibility:** Object parameters allow us to pass only the necessary values and easily extend the parameter list in the future without modifying function signatures or affecting calling code.
- **Readability:** Passing an object with named properties enhances code readability, especially when dealing with functions that have multiple parameters.

## Examples:

A pretty good example is the auth function.

```JS
import { auth } from "osu-api-extended";

// before
await auth.login(client_id, client_secret); 

// after
await auth.login(method, {
	client_id: 0,
	client_secret: 0,
	scopes: []
}); 
```

### with this kind of upgrade, you can also opt-in for a single auth function.
You can now merge `auth.login()`, `auth.login_lazer()` & `auth.authorize_cli()` into 1 function:

```JS
const method = "lazer"; // could be either "stable", "lazer" or "cli"
data = {
	client_id: 0,
	client_secret: 0,
	
	login: 0,
	password: 0,
	
	callbackUrl: 0,
	scopes: [ 0, 0, 0 ]
};
```

meaning:
- for `method="stable"` you would need `client_id` , `client_secret` & `scopes`.
- for `method="lazer"` you would need `username` & `password`.
- for `method="cli"` you would need `client_id`, `client_secret`,  `callback_url` & `scopes`
 
or you could give up on the method property entirely.
here"s a code example:
```JS
async login(method, data) => {
	if (method === "stable") {
		// perform "stable" auth...
	} else if (method === "lazer") {
		// perform "lazer" auth...
	} else if (method === "cli") {
		// perform "cli" auth...
	} else thow new Error("something went wrong");
}
```

### PR DESCRIPTION
**Pull request by yorunoken**
closes #15

### CODE REVIEW

**Comment by yorunoken** [comment]
bump

**Comment by GabuTheDev** [comment]
You missed something that I've mentioned in #15 

method is not an object property, but a different parameter (the first one to be exact).
so the function will take 2 parameters: method and an object that contains the login informations.


the code example in [your original comment](https://github.com/cyperdark/osu-api-extended/issues/15#issuecomment-1763320789) was good, idk why you've changed it.

(I'm just saying you did not follow my original suggestion; depends on cyperdark if he wants to go with this version or the original version)

**Comment by cyperdark** [comment]
not planned in v2, will implement in v3

**Comment by yorunoken** [comment]
@GabuTheDev wouldn't it make more sense to put `method` inside the object? That's the reason why I put it there

**Comment by GabuTheDev** [comment]
> @GabuTheDev wouldn't it make more sense to put `method` inside the object? That's the reason why I put it there

not really. I grouped the parameters based on types. `method` have no correlation to login info. Also I requested this just because every popular package works in the same way so it's not just my preference but an overall usage.

**Pull request closed without merging**
